services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - denokv
    env_file:
      - .env
    environment:
      - DENO_KV_HOST=http://denokv:4512
    ports:
      - "3000:3000"
    networks:
      - kv_net

  denokv:
    image: ghcr.io/denoland/denokv
    ports:
      - "4512:4512"
    volumes:
      - ./data:/data
    command: --sqlite-path /data/denokv.sqlite serve --access-token ${DENO_KV_ACCESS_TOKEN}
    env_file:
      - .env
    init: true
    networks:
      - kv_net

networks:
  kv_net: